# Generated by Django 4.2.1 on 2023-06-26 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0017_countrydata'),
    ]

    operations = [
        migrations.RenameField(
            model_name='countrydata',
            old_name='population',
            new_name='age',
        ),
        migrations.RenameField(
            model_name='countrydata',
            old_name='country',
            new_name='disease',
        ),
    ]
