# Generated by Django 4.2.1 on 2023-06-26 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0018_rename_population_countrydata_age_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='countrydata',
            options={},
        ),
    ]
