# Generated by Django 4.2.1 on 2023-06-26 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0020_countrydata_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countrydata',
            name='disease',
            field=models.CharField(choices=[('measle', 'Measle'), ('sickness', 'Sickness'), ('flue', 'Flue'), ('others', 'Others')], max_length=100),
        ),
    ]
